name: ref-logistics Deployment

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  ssh-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.REF_HOST }}
          username: ${{ vars.REF_USER }}
          password: ${{ vars.REF_PASSWORD }}
          port: 22
          script: |
            if [ -d "ref-logistics-app-sdk" ]; then
              echo "Repository already exists, cleaning up"
              cd ref-logistics-app-sdk && docker-compose down && cd && sudo rm -rf ref-logistics-app-sdk
            fi
            git clone -b develop https://github.com/Dishab-kaushal/ref-logistics-app-sdk.git && cd ref-logistics-app-sdk && cp ~/.env .env && git submodule init && git submodule update --remote --recursive
            sudo docker-compose up -d --build
            echo "Deployment completed"

      # - name: Deploy to server
      #   env:
      #     SSH_PASSWORD: ${{ secrets.REF_PASSWORD }}
      #   run: |
      #     ssh-keyscan 13.234.207.112  >> ~/.ssh/known_hosts
      #     expect <<EOF
      #     spawn ssh ec2-user@13.234.207.112 "mkdir -p /home/ec2-user/test"
      #     expect "password:"
      #     send "${{ secrets.REF_PASSWORD }}\r"
      #     expect eof
      #     EOF

      # - name: Deploy to Server
      #   env:
      #     HOST: ${{ secrets.REF_HOST }}
      #     USERNAME: ${{ secrets.REF_USER }}
      #     PASSWORD: ${{ secrets.REF_PASSWORD }}
        
      #   run: |
      #     # Install SSH client
      #     sudo apt-get install -y openssh-client

      #     # Clone or update repository
      #     if [ -d "ref-logistics-app-sdk" ]; then
      #       echo "Repository already exists, cleaning up"
      #       cd ./ref-logistics-app-sdk && docker-compose down && sudo rm -rf ./../ref-logistics-app-sdk
      #     else
      #       echo "Cloning repository"
      #       cd /home/ec2-user && git clone -b develop https://github.com/Dishab-kaushal/ref-logistics-app-sdk.git && cd ref-logistics-app-sdk && git submodule init && git submodule update --remote --recursive
      #     fi
          

      # - name: ref-logistics Deployment
      #   env:
      #     HOST: ${{ secrets.REF_HOST }}
      #     USERNAME: ${{ secrets.REF_USER }}
      #     PASSWORD: ${{ secrets.REF_PASSWORD }}
      #   run: |
      #     cd ./ref-logistics-app-sdk
      #     sudo docker-compose up -d --build
      #     echo "deployment completed"




