name: ref-logistics Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ssh-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.REF_HOST }}
          USERNAME: ${{ secrets.REF_USER }}
          PASSWORD: ${{ secrets.REF_PASSWORD }}
        
        run: |
          # Install SSH client
          sudo apt-get install -y openssh-client

          # Clone or update repository
          if [ -d "ref-logistics-app-sdk" ]; then
            echo "Repository already exists, cleaning up"
            cd ./ref-logistics-app-sdk && git pull origin patch-1
          else
            echo "Cloning repository"
            git clone -b patch-1 https://github.com/Dishab-kaushal/ref-logistics-app-sdk.git && cd ref-logistics-app-sdk && git submodule init && git submodule update --remote --recursive
          fi

          # SSH to server and deploy
          sshpass -p $PASSWORD ssh $USERNAME@$HOST << EOF
          cd ./ref-logistics-app-sdk
          cp ~/.env ~/ref-logistics-app-sdk/
          sudo docker-compose up -d --build
          EOF




